### ISSUE TITLE
Add portals to change the blocks

### ISSUE THREAD

**Issue by kadsin** [KadSin/shoot-run#3]
### Description

**Problem:** Current block generating has no realistic feeling.

**Scenario:** Show a moving portal and when the player meets it, Then generate new blocks.

### Tasks

- [x] Show a portal that is moving randomly in all directions on the screen
- [x] Trigger an event when the player meets the portal
- [x] Generate new blocks, reset enemies, and reset the portal location
